name: nba
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  provider: ^6.0.4
  get_it: ^7.2.0
  build_runner: 2.2.1
  flutter_gen_runner: 4.3.0
  injectable_generator: 1.5.4
  json_annotation: ^4.7.0
  flutter_bloc: 7.3.3
  auto_route: ^3.2.0
  injectable: ^1.5.4
  release_updater: ^1.0.24
  path_provider: ^2.0.11
  dio_cache_interceptor: ^2.0.0-beta.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: any
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
